name: Slack Release Payload Builder
description: Build a Slack Block Kit payload from GitHub Release info
inputs:
  APP:
    required: true
    description: Application name
  ENVIRONMENT:
    required: true
    description: Deployment environment
  RELEASE_URL:
    required: true
    description: GitHub release URL
  RELEASE_NAME:
    required: true
    description: GitHub release name (e.g. tag or commit SHA)
  RELEASE_BODY:
    required: false
    description: GitHub release body (for changelog parsing)
  RELEASE_ACTOR:
    required: true
    description: The GitHub actor
  GITHUB_REPO:
    required: true
    description: GitHub repository full name (owner/repo)
  CHANNEL:
    required: true
    description: Slack channel ID
  ARGOCD_URL:
    required: true
    description: Argocd url
outputs:
  slack_payload:
    description: The Slack payload JSON
    value: ${{ steps.generate.outputs.slack_payload }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # pin@5.6.0
      with:
        python-version: '3.12'

    - name: Run payload generation script
      id: generate
      run: |
        python ${{ github.action_path }}/slack_release_payload_builder.py
      shell: bash
      env:
        INPUT_APP: ${{ inputs.APP }}
        INPUT_ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        INPUT_RELEASE_URL: ${{ inputs.RELEASE_URL }}
        INPUT_RELEASE_NAME: ${{ inputs.RELEASE_NAME }}
        INPUT_RELEASE_BODY: ${{ inputs.RELEASE_BODY }}
        INPUT_RELEASE_ACTOR: ${{ inputs.RELEASE_ACTOR }}
        INPUT_GITHUB_REPO: ${{ inputs.GITHUB_REPO }}
        INPUT_CHANNEL: ${{ inputs.CHANNEL }}
        INPUT_ARGOCD_URL: ${{ inputs.ARGOCD_URL }}
